module.exports = [
  { id: 1, artist_name: 'keyshia cole' },
  { id: 2, artist_name: 'alicia keys' },
  { id: 3, artist_name: 'troy' },
  { id: 4, artist_name: 'fall out boy' },
  { id: 5, artist_name: 'kanye west' },
  { id: 6, artist_name: 'colbie caillat' },
  { id: 7, artist_name: 'blue foundation' },
  { id: 8, artist_name: 'the-dream' },
  { id: 9, artist_name: 'maroon 5' },
  { id: 10, artist_name: 'lefty frizzell' },
  { id: 11, artist_name: 'lester flatt' },
  { id: 12, artist_name: 'brownie mcghee' },
  { id: 13, artist_name: 'james otto' },
  { id: 14, artist_name: 'josh abbott band' },
  { id: 15, artist_name: 'lukas nelson and promise of the real' },
  { id: 16, artist_name: 'zac brown band' },
  { id: 17, artist_name: 'buck owens' },
  { id: 18, artist_name: 'keith urban' },
  { id: 19, artist_name: 'easton corbin' },
  { id: 20, artist_name: 'ella fitzgerald' },
  { id: 21, artist_name: 'josh white' },
  { id: 22, artist_name: 'louis prima' },
  { id: 23, artist_name: 'billie holiday' },
  { id: 24, artist_name: 'woody guthrie' },
  { id: 25, artist_name: 'big maybelle' },
  { id: 26, artist_name: 'jimmy reed' },
  { id: 27, artist_name: 'dean martin' },
  { id: 28, artist_name: 'erroll garner' },
  { id: 29, artist_name: 'george shearing' },
  { id: 30, artist_name: 'doris day' },
  { id: 31, artist_name: 'vic damone' },
  { id: 32, artist_name: 'dizzy gillespie' },
  { id: 33, artist_name: 'gerry mulligan' },
  { id: 34, artist_name: 'bing crosby' },
  { id: 35, artist_name: 'ray noble' },
  { id: 36, artist_name: 'stan kenton' },
  { id: 37, artist_name: 'thelonious monk' },
  { id: 38, artist_name: 'the andrews sisters' },
  { id: 39, artist_name: 'tony scott' },
  { id: 40, artist_name: 'buck clayton' },
  { id: 41, artist_name: 'tony bennett' },
  { id: 42, artist_name: 'oscar peterson' },
  { id: 43, artist_name: 'sonny rollins' },
  { id: 44, artist_name: 'marian mcpartland' },
  { id: 45, artist_name: 'louis armstrong' },
  { id: 46, artist_name: 'david benoit' },
  { id: 47, artist_name: 'jungle brothers' },
  { id: 48, artist_name: 'quincy jones' },
  { id: 49, artist_name: 'hiroshima' },
  { id: 50, artist_name: 'dave grusin' },
  { id: 51, artist_name: 'earl klugh' },
  { id: 52, artist_name: 'pestilence' },
  { id: 53, artist_name: 'johnny mercer' },
  { id: 54, artist_name: 'desmond dekker' },
  { id: 55, artist_name: 'the paragons' },
  { id: 56, artist_name: 'phyllis dillon' },
  { id: 57, artist_name: 'the gaylads' },
  { id: 58, artist_name: 'alton ellis' },
  { id: 59, artist_name: 'the heptones' },
  { id: 60, artist_name: 'the tennors' },
  { id: 61, artist_name: 'tommy mccook' },
  { id: 62, artist_name: 'the uniques' },
  { id: 63, artist_name: 'joya landis' },
  { id: 64, artist_name: 'prince buster' },
  { id: 65, artist_name: 'peter tosh' },
  { id: 66, artist_name: 'elvis presley' },
  { id: 67, artist_name: 'gene vincent & his blue caps' },
  { id: 68, artist_name: 'bill haley & his comets' },
  { id: 69, artist_name: 'ray campi' },
  { id: 70, artist_name: 'the everly brothers' },
  { id: 71, artist_name: 'frankie laine' },
  { id: 72, artist_name: 'the platters' },
  { id: 73, artist_name: 'the kingston trio' },
  { id: 74, artist_name: 'barbra streisand' },
  { id: 75, artist_name: 'the beatles' },
  { id: 76, artist_name: 'mavis staples' },
  { id: 77, artist_name: 'david bowie' },
  { id: 78, artist_name: 'the velvet underground' },
  { id: 79, artist_name: 'chicago' },
  { id: 80, artist_name: 'pink floyd' },
  { id: 81, artist_name: 'led zeppelin' },
  { id: 82, artist_name: 'bee gees' },
  { id: 83, artist_name: 'george harrison' },
  { id: 84, artist_name: 'creedence clearwater revival' },
  { id: 85, artist_name: 'yusuf / cat stevens' },
  { id: 86, artist_name: 'carpenters' },
  { id: 87, artist_name: 'rodríguez' },
  { id: 88, artist_name: 'paul mccartney' },
  { id: 89, artist_name: 'chester bennington' },
  { id: 90, artist_name: 'the union underground' },
  { id: 91, artist_name: 'eddie vedder' },
  { id: 92, artist_name: 'pearl jam' },
  { id: 93, artist_name: 'seether' },
  { id: 94, artist_name: 'insane clown posse' },
  { id: 95, artist_name: 'chevelle' },
  { id: 96, artist_name: 'korn' },
  { id: 97, artist_name: 'system of a down' },
  { id: 98, artist_name: 'sly & the family stone' },
  { id: 99, artist_name: 'red hot chili peppers' },
  { id: 100, artist_name: 'trapt' },
  { id: 101, artist_name: 'skillet' },
  { id: 102, artist_name: 'heather victoria' },
  { id: 103, artist_name: 'killah priest' },
  { id: 104, artist_name: 'epmd' },
  { id: 105, artist_name: 'shyheim' },
  { id: 106, artist_name: 'rayess bek' },
  { id: 107, artist_name: 'abstract artform' },
  { id: 108, artist_name: "goin' through" },
  { id: 109, artist_name: 'lil wayne' },
  { id: 110, artist_name: 'black moon' },
  { id: 111, artist_name: 'radioinactive' },
  { id: 112, artist_name: 'zulú hip hop jam' },
  { id: 113, artist_name: 'smif-n-wessun' },
  { id: 114, artist_name: 'krs-one' },
  { id: 115, artist_name: 'armand hammer' },
  { id: 116, artist_name: 'kwest tha madd lad' },
  { id: 117, artist_name: 'styles p' },
  { id: 118, artist_name: 'fat joe' },
  { id: 119, artist_name: 'statik selektah' },
  { id: 120, artist_name: 'goldlink' },
  { id: 121, artist_name: 'abhi the nomad' },
  { id: 122, artist_name: 'big l' },
  { id: 123, artist_name: 'the cross movement' },
  { id: 124, artist_name: 'shyne' },
  { id: 125, artist_name: 'busta rhymes' },
  { id: 126, artist_name: 'mc lyte' },
  { id: 127, artist_name: 'grandmaster flash' },
  { id: 128, artist_name: "ultramagnetic mc's" },
  { id: 129, artist_name: "ol' dirty bastard" },
  { id: 130, artist_name: 'v.i.c.' },
  { id: 131, artist_name: 'black$tar' },
  { id: 132, artist_name: "lil' flip" },
  { id: 133, artist_name: 'talib kweli' },
  { id: 134, artist_name: 'loon' },
  { id: 135, artist_name: 'the lox' },
  { id: 136, artist_name: 'leaders of the new school' },
  { id: 137, artist_name: 'hiphop tamizha' },
  { id: 138, artist_name: 'black rob' },
  { id: 139, artist_name: 'nappy roots' },
  { id: 140, artist_name: 'aaliyah' },
  { id: 141, artist_name: 'will smith' },
  { id: 142, artist_name: 'denzel curry' },
  { id: 143, artist_name: 'french montana' },
  { id: 144, artist_name: 'kurtis blow' },
  { id: 145, artist_name: 'mos def' },
  { id: 146, artist_name: 'cassidy' },
  { id: 147, artist_name: 'eric b. & rakim' },
  { id: 148, artist_name: 't-pain' },
  { id: 149, artist_name: '$uicideboy$' },
  { id: 150, artist_name: 'ghostface killah' },
  { id: 151, artist_name: 'q-tip' },
  { id: 152, artist_name: 'future' },
  { id: 153, artist_name: 'eazy-e' },
  { id: 154, artist_name: 'rakim' },
  { id: 155, artist_name: 'ja rule' },
  { id: 156, artist_name: 'nipsey hussle' },
  { id: 157, artist_name: 'the roots' },
  { id: 158, artist_name: 'mack 10' },
  { id: 159, artist_name: 'm.o.p.' },
  { id: 160, artist_name: 'nine' },
  { id: 161, artist_name: 'jeezy' },
];
