module.exports = [
  { song: "fallin' out", year: '2007', artist_id: 1, genre_id: 1 },
  {
    song: 'lesson learned (feat. john mayer)',
    year: '2007',
    artist_id: 2,
    genre_id: 1,
  },
  { song: 'bet on it', year: '2007', artist_id: 3, genre_id: 1 },
  {
    song: "this ain't a scene, it's an arms race",
    year: '2007',
    artist_id: 4,
    genre_id: 1,
  },
  { song: 'champion', year: '2007', artist_id: 5, genre_id: 1 },
  { song: 'realize', year: '2007', artist_id: 6, genre_id: 1 },
  { song: 'everything i am', year: '2007', artist_id: 5, genre_id: 1 },
  { song: 'i remember', year: '2007', artist_id: 1, genre_id: 1 },
  { song: 'eyes on fire', year: '2007', artist_id: 7, genre_id: 1 },
  { song: 'i luv your girl', year: '2007', artist_id: 8, genre_id: 1 },
  { song: 'wake up call', year: '2007', artist_id: 9, genre_id: 1 },
  {
    song: 'lost love blues (rehearsal session)',
    year: '1951',
    artist_id: 10,
    genre_id: 2,
  },
  { song: "i'll try", year: '1951', artist_id: 10, genre_id: 2 },
  {
    song: 'all of me loves all of you',
    year: '1951',
    artist_id: 10,
    genre_id: 2,
  },
  {
    song: 'no mother in this world today',
    year: '1951',
    artist_id: 11,
    genre_id: 2,
  },
  { song: 'long gone', year: '1951', artist_id: 12, genre_id: 2 },
  {
    song: "i know you're lonesome (while waiting for me)",
    year: '1951',
    artist_id: 10,
    genre_id: 2,
  },
  { song: "that's me without you", year: '1951', artist_id: 10, genre_id: 2 },
  {
    song: "give me the flowers (while i'm living)",
    year: '1951',
    artist_id: 11,
    genre_id: 2,
  },
  { song: 'gone home', year: '1951', artist_id: 11, genre_id: 2 },
  { song: 'i still miss someone', year: '1951', artist_id: 11, genre_id: 2 },
  {
    song: "don't stay away (till love grows cold)",
    year: '1951',
    artist_id: 10,
    genre_id: 2,
  },
  { song: 'who will sing for me?', year: '1951', artist_id: 11, genre_id: 2 },
  { song: 'he took your place', year: '1951', artist_id: 11, genre_id: 2 },
  { song: 'forever (and always)', year: '1951', artist_id: 10, genre_id: 2 },
  { song: 'black snake moan', year: '1951', artist_id: 12, genre_id: 2 },
  { song: 'soldiers & jesus', year: '2010', artist_id: 13, genre_id: 2 },
  { song: 'all of a sudden', year: '2010', artist_id: 14, genre_id: 2 },
  {
    song: 'pali gap / hey baby (new rising sun)',
    year: '2010',
    artist_id: 15,
    genre_id: 2,
  },
  { song: 'no hurry', year: '2010', artist_id: 16, genre_id: 2 },
  {
    song: 'colder weather (feat. little big town)',
    year: '2010',
    artist_id: 16,
    genre_id: 2,
  },
  { song: 'martin', year: '2010', artist_id: 16, genre_id: 2 },
  { song: 'together again', year: '2010', artist_id: 17, genre_id: 2 },
  { song: 'nothing', year: '2010', artist_id: 16, genre_id: 2 },
  { song: 'all for you', year: '2010', artist_id: 18, genre_id: 2 },
  {
    song: "a lot to learn about livin'",
    year: '2010',
    artist_id: 19,
    genre_id: 2,
  },
  { song: 'soon', year: '1950', artist_id: 20, genre_id: 3 },
  { song: 'call me darling', year: '1951', artist_id: 21, genre_id: 3 },
  {
    song: 'the bigger the figure (with keely smith)',
    year: '1951',
    artist_id: 22,
    genre_id: 3,
  },
  { song: 'one mint julep', year: '1951', artist_id: 22, genre_id: 3 },
  { song: 'eleanor', year: '1951', artist_id: 22, genre_id: 3 },
  { song: 'basta', year: '1951', artist_id: 22, genre_id: 3 },
  {
    song: "you'll have to swing it (mr. paganini)",
    year: '1953',
    artist_id: 20,
    genre_id: 3,
  },
  {
    song: 'it might as well be spring',
    year: '1953',
    artist_id: 20,
    genre_id: 3,
  },
  { song: 'thanks for the memory', year: '1953', artist_id: 20, genre_id: 3 },
  { song: 'lover, come back to me', year: '1953', artist_id: 20, genre_id: 3 },
  { song: 'taking a chance on love', year: '1953', artist_id: 20, genre_id: 3 },
  {
    song: 'between the devil and the deep blue sea',
    year: '1953',
    artist_id: 20,
    genre_id: 3,
  },
  { song: 'yesterdays', year: '1953', artist_id: 23, genre_id: 3 },
  { song: "i can't face the music", year: '1953', artist_id: 23, genre_id: 3 },
  { song: 'remember', year: '1953', artist_id: 23, genre_id: 3 },
  { song: 'let yourself go', year: '1958', artist_id: 20, genre_id: 3 },
  { song: 'dance around', year: '1958', artist_id: 24, genre_id: 3 },
  {
    song: 'you keep coming back like a song',
    year: '1958',
    artist_id: 20,
    genre_id: 3,
  },
  {
    song: 'top hat, white tie, and tails',
    year: '1958',
    artist_id: 20,
    genre_id: 3,
  },
  {
    song: "i can't give you anything but love",
    year: '1958',
    artist_id: 20,
    genre_id: 3,
  },
  { song: 'sweet and lovely', year: '1958', artist_id: 20, genre_id: 3 },
  {
    song: "i'm putting all my eggs in one basket",
    year: '1958',
    artist_id: 20,
    genre_id: 3,
  },
  { song: 'pitiful', year: '1958', artist_id: 25, genre_id: 3 },
  {
    song: 'put your finger in the air',
    year: '1958',
    artist_id: 24,
    genre_id: 3,
  },
  { song: "you're something else", year: '1958', artist_id: 26, genre_id: 3 },
  { song: 'go on to school', year: '1958', artist_id: 26, genre_id: 3 },
  { song: 'supper time', year: '1958', artist_id: 20, genre_id: 3 },
  {
    song: "alexander's ragtime band",
    year: '1958',
    artist_id: 20,
    genre_id: 3,
  },
  { song: 'the song is ended', year: '1958', artist_id: 20, genre_id: 3 },
  { song: 'the money song', year: '1950', artist_id: 27, genre_id: 4 },
  {
    song: "i don't care if the sun don't shine",
    year: '1950',
    artist_id: 27,
    genre_id: 4,
  },
  {
    song: "i don't know why (i just do)",
    year: '1950',
    artist_id: 28,
    genre_id: 4,
  },
  { song: "i'll remember april", year: '1950', artist_id: 29, genre_id: 4 },
  { song: 'here in my arms', year: '1950', artist_id: 30, genre_id: 4 },
  { song: 'an affair to remember', year: '1950', artist_id: 31, genre_id: 4 },
  { song: 'conception', year: '1950', artist_id: 29, genre_id: 4 },
  { song: 'september in the rain', year: '1950', artist_id: 29, genre_id: 4 },
  { song: 'pick yourself up', year: '1950', artist_id: 29, genre_id: 4 },
  { song: 'oh me! oh my! oh you!', year: '1950', artist_id: 30, genre_id: 4 },
  { song: 'i know that you know', year: '1950', artist_id: 30, genre_id: 4 },
  { song: 'muskrat ramble', year: '1950', artist_id: 27, genre_id: 4 },
  { song: 'that certain party', year: '1950', artist_id: 27, genre_id: 4 },
  { song: 'love me, pretty baby', year: '1951', artist_id: 32, genre_id: 4 },
  { song: "mulligan's too", year: '1951', artist_id: 33, genre_id: 4 },
  { song: 'i ran all the way home', year: '1951', artist_id: 27, genre_id: 4 },
  { song: 'christmas story', year: '1951', artist_id: 30, genre_id: 4 },
  {
    song: "you're getting to be a habit with me",
    year: '1951',
    artist_id: 30,
    genre_id: 4,
  },
  {
    song: "santa claus is comin' to town",
    year: '1951',
    artist_id: 34,
    genre_id: 4,
  },
  { song: "sailors' polka", year: '1951', artist_id: 27, genre_id: 4 },
  {
    song: 'love is the sweetest thing',
    year: '1951',
    artist_id: 35,
    genre_id: 4,
  },
  { song: 'yesterdays', year: '1951', artist_id: 36, genre_id: 4 },
  { song: 'solitaire', year: '1951', artist_id: 27, genre_id: 4 },
  { song: 'moonlight bay', year: '1951', artist_id: 30, genre_id: 4 },
  { song: 'if', year: '1951', artist_id: 27, genre_id: 4 },
  { song: "monk's mood", year: '1951', artist_id: 37, genre_id: 4 },
  { song: 'winter wonderland', year: '1951', artist_id: 38, genre_id: 4 },
  { song: 'school days', year: '1951', artist_id: 32, genre_id: 4 },
  {
    song: "i'll always love you (day after day)",
    year: '1951',
    artist_id: 27,
    genre_id: 4,
  },
  { song: 'as you are', year: '1952', artist_id: 27, genre_id: 4 },
  { song: "it's you or no one", year: '1953', artist_id: 39, genre_id: 4 },
  {
    song: 'swing low...sweet cadillac',
    year: '1953',
    artist_id: 32,
    genre_id: 4,
  },
  { song: 'jayhawk', year: '1953', artist_id: 40, genre_id: 4 },
  { song: 'winter wonderland', year: '1953', artist_id: 41, genre_id: 4 },
  { song: 'the christmas waltz', year: '1953', artist_id: 30, genre_id: 4 },
  { song: 'the nearness of you', year: '1953', artist_id: 33, genre_id: 4 },
  { song: 'i was doing all right', year: '1953', artist_id: 42, genre_id: 4 },
  {
    song: "i've got you under my skin",
    year: '1953',
    artist_id: 42,
    genre_id: 4,
  },
  { song: 'i know', year: '1953', artist_id: 43, genre_id: 4 },
  { song: 'lullaby of birdland', year: '1953', artist_id: 28, genre_id: 4 },
  { song: 'love is here to stay', year: '1953', artist_id: 44, genre_id: 4 },
  {
    song: "my bucket's got a hole in it",
    year: '1989',
    artist_id: 45,
    genre_id: 4,
  },
  {
    song: 'cast your fate to the wind',
    year: '1989',
    artist_id: 46,
    genre_id: 4,
  },
  { song: "j. beez comin' through", year: '1989', artist_id: 47, genre_id: 4 },
  { song: "i don't go for that", year: '1989', artist_id: 48, genre_id: 4 },
  { song: 'you and me', year: '1989', artist_id: 49, genre_id: 4 },
  { song: 'punta del soul', year: '1989', artist_id: 50, genre_id: 4 },
  { song: 'whisper and promises', year: '1989', artist_id: 51, genre_id: 4 },
  { song: 'the golden age', year: '1989', artist_id: 49, genre_id: 4 },
  { song: 'out of the body', year: '1989', artist_id: 52, genre_id: 4 },
  { song: 'candy', year: '1989', artist_id: 53, genre_id: 4 },
  { song: 'unity', year: '1967', artist_id: 54, genre_id: 5 },
  { song: 'rude boy train', year: '1967', artist_id: 54, genre_id: 5 },
  { song: 'blackbird singing', year: '1967', artist_id: 55, genre_id: 5 },
  { song: 'wiseman', year: '1967', artist_id: 54, genre_id: 5 },
  { song: "don't stay away", year: '1967', artist_id: 56, genre_id: 5 },
  {
    song: 'the first time i saw you',
    year: '1967',
    artist_id: 55,
    genre_id: 5,
  },
  { song: 'she want it', year: '1967', artist_id: 57, genre_id: 5 },
  { song: "don't touch me tomato", year: '1967', artist_id: 56, genre_id: 5 },
  { song: 'why', year: '1967', artist_id: 58, genre_id: 5 },
  { song: 'perfidia', year: '1967', artist_id: 56, genre_id: 5 },
  { song: 'breaking up', year: '1968', artist_id: 58, genre_id: 5 },
  { song: 'willow tree', year: '1968', artist_id: 58, genre_id: 5 },
  { song: 'in love with you', year: '1968', artist_id: 59, genre_id: 5 },
  { song: "i can't stand it", year: '1968', artist_id: 58, genre_id: 5 },
  { song: 'i want everything', year: '1968', artist_id: 60, genre_id: 5 },
  { song: 'ride your donkey', year: '1968', artist_id: 60, genre_id: 5 },
  {
    song: 'what the world needs now is love',
    year: '1968',
    artist_id: 61,
    genre_id: 5,
  },
  {
    song: "out of love (i'm the one love forgot)",
    year: '1968',
    artist_id: 62,
    genre_id: 5,
  },
  { song: 'love is all i had', year: '1968', artist_id: 56, genre_id: 5 },
  { song: 'angel of the morning', year: '1968', artist_id: 63, genre_id: 5 },
  { song: 'moonlight lover', year: '1968', artist_id: 63, genre_id: 5 },
  { song: 'rough rider', year: '1968', artist_id: 64, genre_id: 5 },
  { song: 'equal rights', year: '1968', artist_id: 65, genre_id: 5 },
  { song: 'love me', year: '1956', artist_id: 66, genre_id: 6 },
  { song: 'ready teddy', year: '1956', artist_id: 66, genre_id: 6 },
  { song: "i'm counting on you", year: '1956', artist_id: 66, genre_id: 6 },
  { song: 'i flipped', year: '1956', artist_id: 67, genre_id: 6 },
  { song: 'jezebel', year: '1956', artist_id: 67, genre_id: 6 },
  {
    song: 'jumps, giggles and shouts',
    year: '1956',
    artist_id: 67,
    genre_id: 6,
  },
  { song: 'hot dog, buddy, buddy', year: '1956', artist_id: 68, genre_id: 6 },
  { song: "ain't she sweet", year: '1956', artist_id: 67, genre_id: 6 },
  { song: 'the crossing', year: '1957', artist_id: 69, genre_id: 6 },
  { song: "you can't catch me", year: '1957', artist_id: 69, genre_id: 6 },
  {
    song: "i didn't mean to be mean",
    year: '1957',
    artist_id: 69,
    genre_id: 6,
  },
  { song: "it ain't me", year: '1957', artist_id: 69, genre_id: 6 },
  { song: 'give that love to me', year: '1957', artist_id: 69, genre_id: 6 },
  { song: 'loretta', year: '1957', artist_id: 69, genre_id: 6 },
  { song: 'when will i be loved', year: '1957', artist_id: 70, genre_id: 6 },
  { song: "that ain't right", year: '1957', artist_id: 71, genre_id: 6 },
  { song: "don't forget", year: '1957', artist_id: 72, genre_id: 6 },
  { song: 'o promise me', year: '1957', artist_id: 72, genre_id: 6 },
  { song: 'time and tide', year: '1957', artist_id: 72, genre_id: 6 },
  {
    song: "darktown strutter's ball",
    year: '1957',
    artist_id: 72,
    genre_id: 6,
  },
  { song: "rockin' chair", year: '1957', artist_id: 71, genre_id: 6 },
  {
    song: "i'll be home for christmas",
    year: '1957',
    artist_id: 66,
    genre_id: 6,
  },
  { song: 'blueberry hill', year: '1957', artist_id: 66, genre_id: 6 },
  { song: 'happy ending', year: '1963', artist_id: 66, genre_id: 6 },
  { song: 'cotton candy land', year: '1963', artist_id: 66, genre_id: 6 },
  { song: 'try to remember', year: '1963', artist_id: 73, genre_id: 6 },
  {
    song: 'happy days are here again',
    year: '1963',
    artist_id: 74,
    genre_id: 6,
  },
  { song: 'fame and fortune', year: '1963', artist_id: 66, genre_id: 6 },
  { song: 'surrender', year: '1963', artist_id: 66, genre_id: 6 },
  { song: 'not a second time', year: '1963', artist_id: 75, genre_id: 6 },
  { song: "all i've got to do", year: '1963', artist_id: 75, genre_id: 6 },
  {
    song: 'you really got a hold on me',
    year: '1963',
    artist_id: 75,
    genre_id: 6,
  },
  { song: 'till there was you', year: '1963', artist_id: 75, genre_id: 6 },
  { song: 'all my loving', year: '1963', artist_id: 75, genre_id: 6 },
  { song: 'devil in her heart', year: '1963', artist_id: 75, genre_id: 6 },
  { song: 'a taste of honey', year: '1963', artist_id: 75, genre_id: 6 },
  { song: 'hold me tight', year: '1963', artist_id: 75, genre_id: 6 },
  { song: "it's now or never", year: '1963', artist_id: 66, genre_id: 6 },
  { song: 'p.s. i love you', year: '1963', artist_id: 75, genre_id: 6 },
  { song: 'please mister postman', year: '1963', artist_id: 75, genre_id: 6 },
  { song: 'fun in acapulco', year: '1963', artist_id: 66, genre_id: 6 },
  { song: 'i feel so bad', year: '1963', artist_id: 66, genre_id: 6 },
  { song: 'roustabout', year: '1964', artist_id: 66, genre_id: 6 },
  {
    song: 'i have learned to do without you',
    year: '1970',
    artist_id: 76,
    genre_id: 6,
  },
  { song: 'the width of a circle', year: '1970', artist_id: 77, genre_id: 6 },
  { song: 'who loves the sun', year: '1970', artist_id: 78, genre_id: 6 },
  { song: 'sweet jane', year: '1970', artist_id: 78, genre_id: 6 },
  { song: 'colour my world', year: '1970', artist_id: 79, genre_id: 6 },
  { song: 'fat old sun', year: '1970', artist_id: 80, genre_id: 6 },
  { song: 'tangerine', year: '1970', artist_id: 81, genre_id: 6 },
  { song: 'lonely days', year: '1970', artist_id: 82, genre_id: 6 },
  { song: 'make me smile', year: '1970', artist_id: 79, genre_id: 6 },
  { song: 'art of dying', year: '1970', artist_id: 83, genre_id: 6 },
  { song: "isn't it a pity", year: '1970', artist_id: 83, genre_id: 6 },
  { song: "travelin' band", year: '1970', artist_id: 84, genre_id: 6 },
  { song: 'wild world', year: '1970', artist_id: 85, genre_id: 6 },
  { song: 'born to move', year: '1970', artist_id: 84, genre_id: 6 },
  {
    song: "i'll never fall in love again",
    year: '1970',
    artist_id: 86,
    genre_id: 6,
  },
  { song: 'jane s. piddy', year: '1970', artist_id: 87, genre_id: 6 },
  { song: 'the lovely linda', year: '1970', artist_id: 88, genre_id: 6 },
  { song: "sailor's lament", year: '1970', artist_id: 84, genre_id: 6 },
  { song: 'system', year: '2002', artist_id: 89, genre_id: 6 },
  { song: 'across the nation', year: '2002', artist_id: 90, genre_id: 6 },
  {
    song: "you've got to hide your love away",
    year: '2002',
    artist_id: 91,
    genre_id: 6,
  },
  { song: 'i am mine', year: '2002', artist_id: 92, genre_id: 6 },
  { song: 'gasoline', year: '2002', artist_id: 93, genre_id: 6 },
  { song: 'juggalo homies', year: '2002', artist_id: 94, genre_id: 6 },
  { song: 'forfeit', year: '2002', artist_id: 95, genre_id: 6 },
  { song: 'alone i break', year: '2002', artist_id: 96, genre_id: 6 },
  { song: 'f**k the system', year: '2002', artist_id: 97, genre_id: 6 },
  { song: 'mr. jack', year: '2002', artist_id: 97, genre_id: 6 },
  { song: "chic 'n' stu", year: '2002', artist_id: 97, genre_id: 6 },
  { song: 'broken', year: '2002', artist_id: 93, genre_id: 6 },
  {
    song: 'thank you (falettinme be mice elf agin)',
    year: '2002',
    artist_id: 98,
    genre_id: 6,
  },
  {
    song: 'throw away your television',
    year: '2002',
    artist_id: 99,
    genre_id: 6,
  },
  { song: 'still frame', year: '2002', artist_id: 100, genre_id: 6 },
  { song: 'savior', year: '2003', artist_id: 101, genre_id: 6 },
  {
    song: 'not taking you back (feat. rapsody)',
    year: '2011',
    artist_id: 102,
    genre_id: 7,
  },
  { song: 'black august (dark)', year: '2011', artist_id: 103, genre_id: 7 },
  { song: 'come with me', year: '2011', artist_id: 103, genre_id: 7 },
  { song: 'musifixtion', year: '2011', artist_id: 103, genre_id: 7 },
  { song: "when i'm writing", year: '2011', artist_id: 103, genre_id: 7 },
  { song: 'do the damn thing', year: '2011', artist_id: 103, genre_id: 7 },
  { song: 'time', year: '2011', artist_id: 103, genre_id: 7 },
  { song: 'danger zone', year: '2011', artist_id: 104, genre_id: 7 },
  { song: '21st century crisis', year: '2011', artist_id: 105, genre_id: 7 },
  { song: 'deja vu', year: '2011', artist_id: 103, genre_id: 7 },
  { song: 'breathe', year: '2011', artist_id: 103, genre_id: 7 },
  { song: 'robbery', year: '2011', artist_id: 103, genre_id: 7 },
  { song: 'soukout remix', year: '2011', artist_id: 106, genre_id: 7 },
  { song: 'halon remix', year: '2011', artist_id: 106, genre_id: 7 },
  {
    song: 'hip-hop is what i was doing (feat. flo soul & dj platform)',
    year: '2011',
    artist_id: 107,
    genre_id: 7,
  },
  {
    song: 'the showcase (i vitrina)',
    year: '2012',
    artist_id: 108,
    genre_id: 7,
  },
  { song: 'spitter', year: '2014', artist_id: 109, genre_id: 7 },
  { song: 'powaful impak!', year: '2014', artist_id: 110, genre_id: 7 },
  { song: 'left handed cigarettes', year: '2014', artist_id: 111, genre_id: 7 },
  { song: 'hoy', year: '2014', artist_id: 112, genre_id: 7 },
  { song: 'stand strong', year: '2014', artist_id: 113, genre_id: 7 },
  { song: 'mil hojas', year: '2014', artist_id: 112, genre_id: 7 },
  {
    song: 'big up new york (feat. black moon, smif-n-wessun, mad lion, funkmaster flex)',
    year: '2014',
    artist_id: 114,
    genre_id: 7,
  },
  {
    song: 'the rent is too damn high',
    year: '2014',
    artist_id: 115,
    genre_id: 7,
  },
  { song: '718', year: '2014', artist_id: 116, genre_id: 7 },
  {
    song: 'rude boy hip hop (feat. raheem devaughn)',
    year: '2014',
    artist_id: 117,
    genre_id: 7,
  },
  { song: 'lean back', year: '2014', artist_id: 118, genre_id: 7 },
  { song: 'all the way (pimp hop)', year: '2014', artist_id: 119, genre_id: 7 },
  { song: 'hip hop interlude', year: '2014', artist_id: 120, genre_id: 7 },
  { song: 'sneaker juice', year: '2014', artist_id: 121, genre_id: 7 },
  {
    song: "stretch and bobbito show '95",
    year: '2014',
    artist_id: 122,
    genre_id: 7,
  },
  { song: 'cossa nostra', year: '2014', artist_id: 112, genre_id: 7 },
  { song: 'cry no more', year: '2014', artist_id: 123, genre_id: 7 },
  {
    song: 'u da man feat. mad lion & smif-n-wessun',
    year: '2014',
    artist_id: 110,
    genre_id: 7,
  },
  { song: 'the hit', year: '2018', artist_id: 124, genre_id: 7 },
  {
    song: 'the whole world looking at me',
    year: '2018',
    artist_id: 125,
    genre_id: 7,
  },
  { song: 'lyte thee mc', year: '2018', artist_id: 126, genre_id: 7 },
  {
    song: 'style (peter gunn theme)',
    year: '2018',
    artist_id: 127,
    genre_id: 7,
  },
  {
    song: 'ego trippin\' (12" version)',
    year: '2018',
    artist_id: 128,
    genre_id: 7,
  },
  { song: 'i go on', year: '2018', artist_id: 126, genre_id: 7 },
  { song: 'rawhide', year: '2018', artist_id: 129, genre_id: 7 },
  { song: 'bop, bop, bop', year: '2018', artist_id: 130, genre_id: 7 },
  { song: 'get it (remix)', year: '2018', artist_id: 131, genre_id: 7 },
  { song: 'real hip hop', year: '2018', artist_id: 132, genre_id: 7 },
  { song: 'listen!!!', year: '2018', artist_id: 133, genre_id: 7 },
  { song: 'ny weather report', year: '2018', artist_id: 133, genre_id: 7 },
  { song: 'relax your mind', year: '2018', artist_id: 134, genre_id: 7 },
  { song: "you don't know", year: '2018', artist_id: 134, genre_id: 7 },
  { song: 'this aint funny', year: '2018', artist_id: 134, genre_id: 7 },
  { song: 'i wanna thank you', year: '2018', artist_id: 135, genre_id: 7 },
  { song: "what's next", year: '2018', artist_id: 136, genre_id: 7 },
  {
    song: "teachers don't teach us nonsense",
    year: '2018',
    artist_id: 136,
    genre_id: 7,
  },
  { song: 'vaadi nee vaa', year: '2018', artist_id: 137, genre_id: 7 },
  { song: 'smile in ya face', year: '2018', artist_id: 138, genre_id: 7 },
  { song: 'sick & tired', year: '2019', artist_id: 139, genre_id: 7 },
  { song: 'more than a woman', year: '2019', artist_id: 140, genre_id: 7 },
  { song: 'men in black', year: '2019', artist_id: 141, genre_id: 7 },
  { song: 'gook', year: '2019', artist_id: 142, genre_id: 7 },
  { song: 'marble floors', year: '2019', artist_id: 143, genre_id: 7 },
  { song: 'basketball', year: '2019', artist_id: 144, genre_id: 7 },
  { song: 'sex, love & money', year: '2019', artist_id: 145, genre_id: 7 },
  { song: 'a.m. to p.m.', year: '2019', artist_id: 146, genre_id: 7 },
  { song: 'paid in full', year: '2019', artist_id: 147, genre_id: 7 },
  {
    song: 'look at her go (feat. chris brown)',
    year: '2019',
    artist_id: 148,
    genre_id: 7,
  },
  {
    song: "you're now tuning into 66.6 fm with dj rapture (the hottest hour of the evening)",
    year: '2019',
    artist_id: 149,
    genre_id: 7,
  },
  { song: 'iron maiden', year: '2019', artist_id: 150, genre_id: 7 },
  { song: 'life is better', year: '2019', artist_id: 151, genre_id: 7 },
  { song: 'tony montana', year: '2019', artist_id: 152, genre_id: 7 },
  { song: "blowin' trees", year: '2019', artist_id: 139, genre_id: 7 },
  { song: 'eazy-duz-it', year: '2019', artist_id: 153, genre_id: 7 },
  { song: 'when i b on tha mic', year: '2019', artist_id: 154, genre_id: 7 },
  { song: "kill 'em all", year: '2019', artist_id: 155, genre_id: 7 },
  { song: 'hussle in the house', year: '2019', artist_id: 156, genre_id: 7 },
  { song: 'country boyz', year: '2019', artist_id: 139, genre_id: 7 },
  { song: 'the seed (2.0)', year: '2019', artist_id: 157, genre_id: 7 },
  { song: '10 million ways', year: '2019', artist_id: 158, genre_id: 7 },
  {
    song: 'ante up (robbin hoodz theory)',
    year: '2019',
    artist_id: 159,
    genre_id: 7,
  },
  { song: 'whutcha want?', year: '2019', artist_id: 160, genre_id: 7 },
  { song: 'switch', year: '2019', artist_id: 141, genre_id: 7 },
  { song: 'r.i.p.', year: '2019', artist_id: 161, genre_id: 7 },
];
